# Try to find the nlohmannjson library
# NLOHMANNJSON_FOUND - system has NLOHMANNJSON lib
# NLOHMANNJSON_INCLUDE_DIR - the NLOHMANNJSON include directory
# NLOHMANNJSON_LIBRARIES - Libraries needed to use NLOHMANNJSON

if (NLOHMANNJSON_INCLUDE_DIR AND NLOHMANNJSON_LIBRARIES)
    # Already in cache, be silent
    set(NLOHMANNJSON_FIND_QUIETLY TRUE)
endif (NLOHMANNJSON_INCLUDE_DIR AND NLOHMANNJSON_LIBRARIES)

FIND_PATH(NLOHMANNJSON_INCLUDE_DIR NAMES nlohmann/json.hpp )

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(nlohmannjson DEFAULT_MSG NLOHMANNJSON_INCLUDE_DIR)