# Try to find the SPOGBFV library
# SPOGBFV_FOUND - system has SPOGBFV lib
# SPOGBFV_INCLUDE_DIR - the SPOGBFV include directory
# SPOGBFV_LIBRARIES - Libraries needed to use SPOGBFV

if (SPOGBFV_INCLUDE_DIR AND SPOGBFV_LIBRARIES)
    # Already in cache, be silent
    set(SPOGBFV_FIND_QUIETLY TRUE)
endif (SPOGBFV_INCLUDE_DIR AND SPOGBFV_LIBRARIES)

FIND_LIBRARY(SPOGBFV_LIBRARIES NAMES spogbfv libspogbfv )
MESSAGE(STATUS "SPOGBFV libs: " ${SPOGBFV_LIBRARIES})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPOGBFV DEFAULT_MSG SPOGBFV_INCLUDE_DIR SPOGBFV_LIBRARIES)